[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = ["lib/solady=/solady"]

[fmt]
bracket_spacing = true


[invariant]
runs = 5000
depth = 32
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
